spring.application.name=literalura
spring.main.web-application-type=none
spring.config.import=optional:file:./application-local.properties,optional:classpath:application-local.properties

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/literalura}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
